apiVersion: apps/v1
kind: Deployment

metadata:
  name: backend-deployment

spec:
  replicas: 1

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
        - name: backend
          image: europe-west1-docker.pkg.dev/laborator4-ci-cd-do/lab4-docker-repo/voting-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000